[package]
authors = ["you"]
description = "A Tauri App"
edition = "2021"
license = ""
name = "copy_clip"
repository = ""
version = "0.3.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
directories = "5.0.0"
base64 = "0.21.0"
flate2 = "1.0"
chrono = "0.4.24"
clipboard-master = "3.1.3"
fern = "0.6"
log = "0.4"
moka = { version = "0.10.2", features = ["future"] }
once_cell = "1.17.1"
regex = "1.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = {version = "0.7.2", features = ["sqlite", "runtime-tokio-rustls"] }
sublime_fuzzy = "0.7.0"
tauri = {version = "1.2.5", features = ["api-all", "clipboard", "global-shortcut", "notification", "system-tray"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
