[package]
authors = ["you"]
description = "A Tauri App"
edition = "2021"
license = ""
name = "copy_clip"
repository = ""
version = "0.3.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = {version = "1.2", features = [] }

[dependencies]
clipboard-master = "3.1.3"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlite = "0.30.4"
sublime_fuzzy = "0.7.0"
tauri = {version = "1.2.4", features = ["api-all", "clipboard", "global-shortcut", "notification", "system-tray"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "z" # Optimize for binary size
strip = true # Remove debug symbols
