[package]
authors = [
    "Zifan Hua <zifan.hua@icloud.com>",
    "Chloe1222 <chloekeyiw@gmail.com>",
]
description = "A feature-rich clipboard manager for Windows, Linux and macOS."
edition = "2021"
license = "MIT"
name = "copy_clip"
repository = "https://github.com/Alex222222222222/CopyClip"
documentation = "https://github.com/Alex222222222222/CopyClip"
homepage = "https://github.com/Alex222222222222/CopyClip"
readme = "README.md"
version = "0.3.8"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
futures = "0.3"
unicode-segmentation = "1.10.1"
unicode-width = "0.1.11"
directories = "5.0.0"
base64 = "0.21.5"
flate2 = "1.0"
chrono = "0.4.24"
clipboard-master = "3.1.3"
fern = "0.6"
log = "0.4"
moka = { version = "0.10.2", features = ["future"] }
once_cell = "1.17.1"
regex = "1.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio-rustls"] }
sublime_fuzzy = "0.7.0"
tauri = { version = "1.5.4", features = [
    "api-all",
    "icon-png",
    "icon-ico",
    "config-toml",
    "config-json5",
    "windows7-compat",
    "fs-extract-api",
    "process-relaunch-dangerous-allow-symlink-macos",
    "process-command-api",
    "clipboard",
    "global-shortcut",
    "system-tray",
    "notification",
] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
