version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/src-clip"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/tauri-plugin-logging"
    schedule:
      interval: "weekly"
