version: 2
updates:
  # Enable version updates for Node.js dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for rust
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
