# build the app for pre-release

name: Pre-release Publish

on:
  workflow_run:
    workflows: [Pre-release Build]
    types:
      - completed

jobs:
  publish:
    name: Publish the package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: make out directory
        run: mkdir out
      
      - uses: actions/download-artifact@v3
        with:
          path: out
      
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            out/*